spring.datasource.url=jdbc:postgresql://dpg-d8l2eod8nd3s73dqmu8g-a/aprendeya
spring.datasource.username=aprendeya_user
spring.datasource.password=6NkvMIhiIRXJjNfafqPrhH8tD2VL9jMs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8082